// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_pharmacie.Data;

#nullable disable

namespace project_pharmacie.Migrations
{
    [DbContext(typeof(PharmacieDbContext))]
    partial class PharmacieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project_pharmacie.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PersonalizedOffer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("project_pharmacie.Models.Commande", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FournisseurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Note")
                        .HasColumnType("float");

                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PrixTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("project_pharmacie.Models.CommandeLigne", b =>
                {
                    b.Property<string>("CommandeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProduitReference")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("CommandeId", "ProduitReference");

                    b.HasIndex("ProduitReference");

                    b.ToTable("CommandeLignes");
                });

            modelBuilder.Entity("project_pharmacie.Models.Facture", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VenteId")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("project_pharmacie.Models.Fournisseur", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("NoteGlobale")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("project_pharmacie.Models.FournisseurProduit", b =>
                {
                    b.Property<string>("FournisseurId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProduitReference")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FournisseurId", "ProduitReference");

                    b.HasIndex("ProduitReference");

                    b.ToTable("FournisseurProduits");
                });

            modelBuilder.Entity("project_pharmacie.Models.Produit", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DatePeremption")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Reference");

                    b.HasIndex("PersonnelId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("project_pharmacie.Models.Utilisateur", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("UserType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("project_pharmacie.Models.Vente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("project_pharmacie.Models.VenteLigne", b =>
                {
                    b.Property<string>("VenteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProduitReference")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("VenteId", "ProduitReference");

                    b.HasIndex("ProduitReference");

                    b.ToTable("VenteLignes");
                });

            modelBuilder.Entity("project_pharmacie.Models.Administrateur", b =>
                {
                    b.HasBaseType("project_pharmacie.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("ADMIN");
                });

            modelBuilder.Entity("project_pharmacie.Models.Personnel", b =>
                {
                    b.HasBaseType("project_pharmacie.Models.Utilisateur");

                    b.Property<string>("AdministrateurId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("AdministrateurId");

                    b.HasDiscriminator().HasValue("PERSONNEL");
                });

            modelBuilder.Entity("project_pharmacie.Models.Commande", b =>
                {
                    b.HasOne("project_pharmacie.Models.Fournisseur", "Fournisseur")
                        .WithMany("Commandes")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_pharmacie.Models.Personnel", "Personnel")
                        .WithMany("CommandesPassees")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fournisseur");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("project_pharmacie.Models.CommandeLigne", b =>
                {
                    b.HasOne("project_pharmacie.Models.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_pharmacie.Models.Produit", "Produit")
                        .WithMany("CommandeLignes")
                        .HasForeignKey("ProduitReference")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("project_pharmacie.Models.Facture", b =>
                {
                    b.HasOne("project_pharmacie.Models.Vente", "Vente")
                        .WithOne("Facture")
                        .HasForeignKey("project_pharmacie.Models.Facture", "VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("project_pharmacie.Models.FournisseurProduit", b =>
                {
                    b.HasOne("project_pharmacie.Models.Fournisseur", "Fournisseur")
                        .WithMany("Produits")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_pharmacie.Models.Produit", "Produit")
                        .WithMany("Fournisseurs")
                        .HasForeignKey("ProduitReference")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("project_pharmacie.Models.Produit", b =>
                {
                    b.HasOne("project_pharmacie.Models.Personnel", "Personnel")
                        .WithMany("ProduitsGeres")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("project_pharmacie.Models.Vente", b =>
                {
                    b.HasOne("project_pharmacie.Models.Client", "Client")
                        .WithMany("Ventes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("project_pharmacie.Models.VenteLigne", b =>
                {
                    b.HasOne("project_pharmacie.Models.Produit", "Produit")
                        .WithMany("VenteLignes")
                        .HasForeignKey("ProduitReference")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_pharmacie.Models.Vente", "Vente")
                        .WithMany("Lignes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("project_pharmacie.Models.Personnel", b =>
                {
                    b.HasOne("project_pharmacie.Models.Administrateur", "Administrateur")
                        .WithMany("Personnels")
                        .HasForeignKey("AdministrateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Administrateur");
                });

            modelBuilder.Entity("project_pharmacie.Models.Client", b =>
                {
                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("project_pharmacie.Models.Commande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("project_pharmacie.Models.Fournisseur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("project_pharmacie.Models.Produit", b =>
                {
                    b.Navigation("CommandeLignes");

                    b.Navigation("Fournisseurs");

                    b.Navigation("VenteLignes");
                });

            modelBuilder.Entity("project_pharmacie.Models.Vente", b =>
                {
                    b.Navigation("Facture");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("project_pharmacie.Models.Administrateur", b =>
                {
                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("project_pharmacie.Models.Personnel", b =>
                {
                    b.Navigation("CommandesPassees");

                    b.Navigation("ProduitsGeres");
                });
#pragma warning restore 612, 618
        }
    }
}
